### ISSUE TITLE
Chirpstack?

### ISSUE THREAD

**Issue by Westiewombat** [things4u/ESP-1ch-Gateway-v6.0#98]
Is it possible to use this gateway for a local (docker) Chirpstack setup? 

I tried adding the following to the config of the gateway to point to the Chirpstack gateway bridge
#define _THINGSERVER "192.168.1.89" // Server URL of the LoRa udp.js server program
#define _THINGPORT 1700 // Your UDP server should listen to this port

I'm using a Heltech ESPv32 V2 for the gateway and and MCCI LMIC node with RFM95W on pro mini

**Comment by platenspeler** [comment]
Hi,

Yes, I do not have experience with Chirpstack but as long as the MQTT server IP address is reachable you should be OK.

the 192.168.1.89 address you use is the internal IP address of type Class C, probably your home address. The the IP address of the real server URL, which could be a  sort of the same depending where your Chirpstack server is.

**Comment by Westiewombat** [comment]
I have had success using ABP on Chirpstack. I needed to tell Chirpstack gateway bridge I was using a semtech packet forwarder....In chirpstack-gateway-bridge.toml
```
[backend]
type="semtech_udp"
[backend.semtech_udp]
  udp_bind = "0.0.0.0:1700"
  skip_crc_check = false
  fake_rx_time=false

``````
and in gateway configGway.h
```
`#define _THINGSERVER "192.168.1.89" // Server URL of the LoRa udp.js server program

#define _THINGPORT 1883 // Your UDP server should listen to this port`
```

I had no luck with OTA
